/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGoogleFitOracle,
  IGoogleFitOracleInterface,
} from "../../../contracts/interfaces/IGoogleFitOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "_date",
        type: "uint64",
      },
    ],
    name: "isDataVerified",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "_steps",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "_calories",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "_heartRate",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "_timestamp",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "_signature",
        type: "bytes",
      },
    ],
    name: "verifyHealthData",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGoogleFitOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IGoogleFitOracleInterface {
    return new Interface(_abi) as IGoogleFitOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGoogleFitOracle {
    return new Contract(address, _abi, runner) as unknown as IGoogleFitOracle;
  }
}
