/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGoogleFitOracle__factory } from "./IGoogleFitOracle__factory";
export { IHealthToken__factory } from "./IHealthToken__factory";
