/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace HealthVerse {
      
    export type HealthDataStruct = {steps: BigNumberish, calories: BigNumberish, heartRate: BigNumberish, timestamp: BigNumberish}

    export type HealthDataStructOutput = [steps: bigint, calories: bigint, heartRate: bigint, timestamp: bigint] & {steps: bigint, calories: bigint, heartRate: bigint, timestamp: bigint }
  
    }

  export interface HealthVerseInterface extends Interface {
    getFunction(nameOrSignature: "addHealthData" | "getAllHealthData" | "getLatestHealthData"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "HealthDataAdded"): EventFragment;

    encodeFunctionData(functionFragment: 'addHealthData', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllHealthData', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getLatestHealthData', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addHealthData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllHealthData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLatestHealthData', data: BytesLike): Result;
  }

  
    export namespace HealthDataAddedEvent {
      export type InputTuple = [user: AddressLike, steps: BigNumberish, calories: BigNumberish, heartRate: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [user: string, steps: bigint, calories: bigint, heartRate: bigint, timestamp: bigint];
      export interface OutputObject {user: string, steps: bigint, calories: bigint, heartRate: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HealthVerse extends BaseContract {
    
    connect(runner?: ContractRunner | null): HealthVerse;
    waitForDeployment(): Promise<this>;

    interface: HealthVerseInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addHealthData: TypedContractMethod<
      [_steps: BigNumberish, _calories: BigNumberish, _heartRate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllHealthData: TypedContractMethod<
      [_user: AddressLike, ],
      [HealthVerse.HealthDataStructOutput[]],
      'view'
    >
    

    
    getLatestHealthData: TypedContractMethod<
      [_user: AddressLike, ],
      [HealthVerse.HealthDataStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addHealthData'): TypedContractMethod<
      [_steps: BigNumberish, _calories: BigNumberish, _heartRate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllHealthData'): TypedContractMethod<
      [_user: AddressLike, ],
      [HealthVerse.HealthDataStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getLatestHealthData'): TypedContractMethod<
      [_user: AddressLike, ],
      [HealthVerse.HealthDataStructOutput],
      'view'
    >;

    getEvent(key: 'HealthDataAdded'): TypedContractEvent<HealthDataAddedEvent.InputTuple, HealthDataAddedEvent.OutputTuple, HealthDataAddedEvent.OutputObject>;

    filters: {
      
      'HealthDataAdded(address,uint256,uint256,uint256,uint256)': TypedContractEvent<HealthDataAddedEvent.InputTuple, HealthDataAddedEvent.OutputTuple, HealthDataAddedEvent.OutputObject>;
      HealthDataAdded: TypedContractEvent<HealthDataAddedEvent.InputTuple, HealthDataAddedEvent.OutputTuple, HealthDataAddedEvent.OutputObject>;
    
    };
  }