/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IGoogleFitOracleInterface extends Interface {
  getFunction(
    nameOrSignature: "isDataVerified" | "verifyHealthData"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isDataVerified",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHealthData",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "isDataVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyHealthData",
    data: BytesLike
  ): Result;
}

export interface IGoogleFitOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IGoogleFitOracle;
  waitForDeployment(): Promise<this>;

  interface: IGoogleFitOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isDataVerified: TypedContractMethod<
    [_user: AddressLike, _date: BigNumberish],
    [boolean],
    "view"
  >;

  verifyHealthData: TypedContractMethod<
    [
      _user: AddressLike,
      _steps: BigNumberish,
      _calories: BigNumberish,
      _heartRate: BigNumberish,
      _timestamp: BigNumberish,
      _signature: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isDataVerified"
  ): TypedContractMethod<
    [_user: AddressLike, _date: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyHealthData"
  ): TypedContractMethod<
    [
      _user: AddressLike,
      _steps: BigNumberish,
      _calories: BigNumberish,
      _heartRate: BigNumberish,
      _timestamp: BigNumberish,
      _signature: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
