/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGoogleFitOracle } from "./IGoogleFitOracle";
export type { IHealthToken } from "./IHealthToken";
