/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface HealthVerseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DAILY_GOAL_CALORIES"
      | "DAILY_GOAL_STEPS"
      | "REWARD_AMOUNT"
      | "addHealthData"
      | "banUser"
      | "bannedUsers"
      | "claimReward"
      | "contractPaused"
      | "emergencyWithdrawToken"
      | "getContractAddresses"
      | "getDailyData"
      | "getTodayProgress"
      | "getUserStatus"
      | "googleFitOracle"
      | "healthToken"
      | "lastActivityDate"
      | "owner"
      | "pauseContract"
      | "renounceOwnership"
      | "requireOracleVerification"
      | "setHealthToken"
      | "setOracle"
      | "toggleOracleVerification"
      | "transferOwnership"
      | "unbanUser"
      | "unpauseContract"
      | "userDailyData"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractPaused"
      | "EmergencyWithdraw"
      | "HealthDataAdded"
      | "OracleVerificationToggled"
      | "OwnershipTransferred"
      | "RewardClaimed"
      | "UserBanned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DAILY_GOAL_CALORIES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAILY_GOAL_STEPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addHealthData",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "banUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bannedUsers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyData",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTodayProgress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "googleFitOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "healthToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastActivityDate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requireOracleVerification",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setHealthToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleOracleVerification",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unbanUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userDailyData",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DAILY_GOAL_CALORIES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAILY_GOAL_STEPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addHealthData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "banUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bannedUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTodayProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "googleFitOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "healthToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastActivityDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireOracleVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHealthToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleOracleVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unbanUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unpauseContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDailyData",
    data: BytesLike
  ): Result;
}

export namespace ContractPausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [token: string, amount: bigint, to: string];
  export interface OutputObject {
    token: string;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HealthDataAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    steps: BigNumberish,
    calories: BigNumberish,
    date: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    steps: bigint,
    calories: bigint,
    date: bigint
  ];
  export interface OutputObject {
    user: string;
    steps: bigint;
    calories: bigint;
    date: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleVerificationToggledEvent {
  export type InputTuple = [required: boolean];
  export type OutputTuple = [required: boolean];
  export interface OutputObject {
    required: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    rewardAmount: BigNumberish,
    date: BigNumberish
  ];
  export type OutputTuple = [user: string, rewardAmount: bigint, date: bigint];
  export interface OutputObject {
    user: string;
    rewardAmount: bigint;
    date: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserBannedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthVerse extends BaseContract {
  connect(runner?: ContractRunner | null): HealthVerse;
  waitForDeployment(): Promise<this>;

  interface: HealthVerseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DAILY_GOAL_CALORIES: TypedContractMethod<[], [bigint], "view">;

  DAILY_GOAL_STEPS: TypedContractMethod<[], [bigint], "view">;

  REWARD_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  addHealthData: TypedContractMethod<
    [
      _steps: BigNumberish,
      _calories: BigNumberish,
      _heartRate: BigNumberish,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  banUser: TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;

  bannedUsers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  claimReward: TypedContractMethod<[_date: BigNumberish], [void], "nonpayable">;

  contractPaused: TypedContractMethod<[], [boolean], "view">;

  emergencyWithdrawToken: TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getContractAddresses: TypedContractMethod<
    [],
    [[string, string] & { tokenAddress: string; oracleAddress: string }],
    "view"
  >;

  getDailyData: TypedContractMethod<
    [_user: AddressLike, _date: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        steps: bigint;
        calories: bigint;
        rewardStatus: bigint;
        oracleVerified: boolean;
      }
    ],
    "view"
  >;

  getTodayProgress: TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, boolean, boolean, boolean, boolean] & {
        steps: bigint;
        calories: bigint;
        stepsGoalReached: boolean;
        caloriesGoalReached: boolean;
        canClaimReward: boolean;
        oracleVerified: boolean;
      }
    ],
    "view"
  >;

  getUserStatus: TypedContractMethod<
    [_user: AddressLike],
    [
      [boolean, bigint, boolean, boolean] & {
        isBanned: boolean;
        lastActive: bigint;
        isContractPaused: boolean;
        oracleRequired: boolean;
      }
    ],
    "view"
  >;

  googleFitOracle: TypedContractMethod<[], [string], "view">;

  healthToken: TypedContractMethod<[], [string], "view">;

  lastActivityDate: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pauseContract: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requireOracleVerification: TypedContractMethod<[], [boolean], "view">;

  setHealthToken: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  setOracle: TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;

  toggleOracleVerification: TypedContractMethod<
    [_required: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unbanUser: TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;

  unpauseContract: TypedContractMethod<[], [void], "nonpayable">;

  userDailyData: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalSteps: bigint;
        totalCalories: bigint;
        date: bigint;
        rewardClaimed: bigint;
        oracleVerified: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DAILY_GOAL_CALORIES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAILY_GOAL_STEPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addHealthData"
  ): TypedContractMethod<
    [
      _steps: BigNumberish,
      _calories: BigNumberish,
      _heartRate: BigNumberish,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "banUser"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bannedUsers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[_date: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contractPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdrawToken"
  ): TypedContractMethod<
    [_token: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getContractAddresses"
  ): TypedContractMethod<
    [],
    [[string, string] & { tokenAddress: string; oracleAddress: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDailyData"
  ): TypedContractMethod<
    [_user: AddressLike, _date: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        steps: bigint;
        calories: bigint;
        rewardStatus: bigint;
        oracleVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTodayProgress"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, boolean, boolean, boolean, boolean] & {
        steps: bigint;
        calories: bigint;
        stepsGoalReached: boolean;
        caloriesGoalReached: boolean;
        canClaimReward: boolean;
        oracleVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStatus"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [boolean, bigint, boolean, boolean] & {
        isBanned: boolean;
        lastActive: bigint;
        isContractPaused: boolean;
        oracleRequired: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "googleFitOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "healthToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastActivityDate"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseContract"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requireOracleVerification"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setHealthToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleOracleVerification"
  ): TypedContractMethod<[_required: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unbanUser"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpauseContract"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userDailyData"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        totalSteps: bigint;
        totalCalories: bigint;
        date: bigint;
        rewardClaimed: bigint;
        oracleVerified: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ContractPaused"
  ): TypedContractEvent<
    ContractPausedEvent.InputTuple,
    ContractPausedEvent.OutputTuple,
    ContractPausedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "HealthDataAdded"
  ): TypedContractEvent<
    HealthDataAddedEvent.InputTuple,
    HealthDataAddedEvent.OutputTuple,
    HealthDataAddedEvent.OutputObject
  >;
  getEvent(
    key: "OracleVerificationToggled"
  ): TypedContractEvent<
    OracleVerificationToggledEvent.InputTuple,
    OracleVerificationToggledEvent.OutputTuple,
    OracleVerificationToggledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "UserBanned"
  ): TypedContractEvent<
    UserBannedEvent.InputTuple,
    UserBannedEvent.OutputTuple,
    UserBannedEvent.OutputObject
  >;

  filters: {
    "ContractPaused(bool)": TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;
    ContractPaused: TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;

    "EmergencyWithdraw(address,uint256,address)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "HealthDataAdded(address,uint64,uint64,uint64)": TypedContractEvent<
      HealthDataAddedEvent.InputTuple,
      HealthDataAddedEvent.OutputTuple,
      HealthDataAddedEvent.OutputObject
    >;
    HealthDataAdded: TypedContractEvent<
      HealthDataAddedEvent.InputTuple,
      HealthDataAddedEvent.OutputTuple,
      HealthDataAddedEvent.OutputObject
    >;

    "OracleVerificationToggled(bool)": TypedContractEvent<
      OracleVerificationToggledEvent.InputTuple,
      OracleVerificationToggledEvent.OutputTuple,
      OracleVerificationToggledEvent.OutputObject
    >;
    OracleVerificationToggled: TypedContractEvent<
      OracleVerificationToggledEvent.InputTuple,
      OracleVerificationToggledEvent.OutputTuple,
      OracleVerificationToggledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardClaimed(address,uint64,uint64)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "UserBanned(address)": TypedContractEvent<
      UserBannedEvent.InputTuple,
      UserBannedEvent.OutputTuple,
      UserBannedEvent.OutputObject
    >;
    UserBanned: TypedContractEvent<
      UserBannedEvent.InputTuple,
      UserBannedEvent.OutputTuple,
      UserBannedEvent.OutputObject
    >;
  };
}
